let level1;
function initLevel() {
  level1 = new Level(
    [
      new Chicken(),
      new Chicken(),
      new Chicken(),
      new Chicken(),
      new Chicken(),
      new MiniChicken(),
      new MiniChicken(),
      new MiniChicken(),
      new MiniChicken(),
      new MiniChicken(),
    ],
    [],
    [
      new Cloud('img/5_background/layers/4_clouds/2.png', -719),
      new Cloud('img/5_background/layers/4_clouds/1.png', 0),
      new Cloud('img/5_background/layers/4_clouds/2.png', 719),
      new Cloud('img/5_background/layers/4_clouds/1.png', 719 * 2),
      new Cloud('img/5_background/layers/4_clouds/2.png', 719 * 3),
    ],
    [
      new BackgroundObject('img/5_background/layers/air.png', -719),
      new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719),
      new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719),
      new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719),
      new BackgroundObject('img/5_background/layers/air.png', 0),
      new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
      new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
      new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
      new BackgroundObject('img/5_background/layers/air.png', 719),
      new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
      new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
      new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),
      new BackgroundObject('img/5_background/layers/air.png', 719 * 2),
      new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 2),
      new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 2),
      new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 2),
      new BackgroundObject('img/5_background/layers/air.png', 719 * 3),
      new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 3),
      new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 3),
      new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 3),
    ],
    [new Coin(200), new Coin(400), new Coin(600), new Coin(800), new Coin(1000), new Coin(1200), new Coin(1400), new Coin(1600), new Coin(1800), new Coin(2000)],
    [
      new Bottle(300),
      new Bottle(500),
      new Bottle(700),
      new Bottle(900),
      new Bottle(1100),
      new Bottle(1300),
      new Bottle(1500),
      new Bottle(1700),
      new Bottle(1900),
      new Bottle(2100),
    ]
  );
}
