let level1;
function initLevel() {
  level1 = new Level(
    [
      new Chicken(),
      new Chicken(),
      new Chicken(),
      new Chicken(),
      new Chicken(),
      new MiniChicken(),
      new MiniChicken(),
      new MiniChicken(),
      new MiniChicken(),
      new MiniChicken(),
    ],
    [],
    [
      new Cloud('img/5_background/layers/4_clouds/2.png', -719),
      new Cloud('img/5_background/layers/4_clouds/1.png', 0),
      new Cloud('img/5_background/layers/4_clouds/2.png', 719),
      new Cloud('img/5_background/layers/4_clouds/1.png', 719 * 2),
      new Cloud('img/5_background/layers/4_clouds/2.png', 719 * 3),
    ],
    [
      new BackgroundObject('img/5_background/layers/air.png', -719),
      new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719),
      new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719),
      new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719),
      new BackgroundObject('img/5_background/layers/air.png', 0),
      new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
      new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
      new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
      new BackgroundObject('img/5_background/layers/air.png', 719),
      new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
      new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
      new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),
      new BackgroundObject('img/5_background/layers/air.png', 719 * 2),
      new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 2),
      new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 2),
      new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 2),
      new BackgroundObject('img/5_background/layers/air.png', 719 * 3),
      new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 3),
      new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 3),
      new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 3),
    ],
    [
      new Coin(210, 180),
      new Coin(390, 250),
      new Coin(620, 210),
      new Coin(810, 240),
      new Coin(1035, 200),
      new Coin(1220, 230),
      new Coin(1475, 220),
      new Coin(1630, 190),
      new Coin(1805, 250),
      new Coin(1990, 210),
    ],
    [
      new Bottle(300),
      new Bottle(500),
      new Bottle(700),
      new Bottle(900),
      new Bottle(1100),
      new Bottle(1300),
      new Bottle(1500),
      new Bottle(1700),
      new Bottle(1900),
      new Bottle(2100),
    ]
  );
}
